
module.exports.routes = {
  'GET /': 'QponController.main',
  'GET /qpon/search':'QponController.search',
  'GET /qpon/read/:id':'QponController.read',
  'GET /qpon/create': 'QponController.create',
  'POST /qpon/create': 'QponController.create',
  'GET /qpon/update/:id':'QponController.update',
  'POST /qpon/update/:id':'QponController.update',
  'GET /qpon/delete/:id': 'QponController.delete',
  'GET /qpon/list': 'QponController.list',
  'GET /person/create': 'PersonController.create',
  'POST /person/create': 'PersonController.create',
  'GET /person': 'PersonController.list',
  'GET /person/list': 'PersonController.list',
  'GET /person/json': 'PersonController.json',
  'GET /person/read/:id': 'PersonController.read',
  'POST /person/delete/:id': 'PersonController.delete',
  'GET /person/search': 'PersonController.search',
  'GET /person/paginate': 'PersonController.paginate',
    'GET /person/aginate': 'PersonController.aginate',
  'GET /user': 'UserController.login',
  'GET /user/login': 'UserController.login',
  'POST /user/login': 'UserController.login',
  'POST /user/logout': 'UserController.logout',
  'GET /person/:id/consultants': 'PersonController.populate',
  'GET /user/:id/clients': 'UserController.populate',
  'POST /user/:id/clients/add/:fk': 'UserController.add',
  'POST /user/:id/clients/remove/:fk': 'UserController.remove',
};
